#!/bin/bash

basepath=$(cd `dirname $0`; pwd)/public
apachepath=$(grep -R "DocumentRoot" /etc/apache2/sites-enabled)
webpath=${apachepath#*DocumentRoot}
webpre=${webpath%/*}

echo "Blog/public的目录为："  $basepath
echo "网站根目录的服目录为： " $webpre

sudo rm -rf $webpath

cp -r $basepath $webpre/
mv $webpre/public $webpre/html

echo "成功！"
